package com.stackanlyze.drinkunoflip.ui.theme

import androidx.compose.ui.graphics.Color

// light colors
val primaryLight = Color(0xFF2C1246)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF4E3468)
val onPrimaryContainerLight = Color(0xFFE6CAFF)
val secondaryLight = Color(0xFF665971)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF2E0FD)
val onSecondaryContainerLight = Color(0xFF52455C)
val tertiaryLight = Color(0xFF3D0B26)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF652C47)
val onTertiaryContainerLight = Color(0xFFFFC4DB)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEF7FD)
val onBackgroundLight = Color(0xFF1D1B1F)
val surfaceLight = Color(0xFFFEF7FD)
val onSurfaceLight = Color(0xFF1D1B1F)
val surfaceVariantLight = Color(0xFFE9DFEB)
val onSurfaceVariantLight = Color(0xFF4A454E)
val outlineLight = Color(0xFF7C757F)
val outlineVariantLight = Color(0xFFCDC3CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F33)
val inverseOnSurfaceLight = Color(0xFFF6EFF4)
val inversePrimaryLight = Color(0xFFDBB9F8)
val surfaceDimLight = Color(0xFFDFD8DD)
val surfaceBrightLight = Color(0xFFFEF7FD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF9F2F7)
val surfaceContainerLight = Color(0xFFF3ECF1)
val surfaceContainerHighLight = Color(0xFFEDE6EC)
val surfaceContainerHighestLight = Color(0xFFE7E0E6)

// dark colors
val primaryDark = Color(0xFFDBB9F8)
val onPrimaryDark = Color(0xFF3E2458)
val primaryContainerDark = Color(0xFF361C50)
val onPrimaryContainerDark = Color(0xFFC8A8E5)
val secondaryDark = Color(0xFFD1C1DC)
val onSecondaryDark = Color(0xFF372C41)
val secondaryContainerDark = Color(0xFF44384E)
val onSecondaryContainerDark = Color(0xFFDBCAE6)
val tertiaryDark = Color(0xFFFFB0D0)
val onTertiaryDark = Color(0xFF531D38)
val tertiaryContainerDark = Color(0xFF4A1530)
val onTertiaryContainerDark = Color(0xFFEB9EBF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF151216)
val onBackgroundDark = Color(0xFFE7E0E6)
val surfaceDark = Color(0xFF151216)
val onSurfaceDark = Color(0xFFE7E0E6)
val surfaceVariantDark = Color(0xFF4A454E)
val onSurfaceVariantDark = Color(0xFFCDC3CF)
val outlineDark = Color(0xFF968E99)
val outlineVariantDark = Color(0xFF4A454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E0E6)
val inverseOnSurfaceDark = Color(0xFF322F33)
val inversePrimaryDark = Color(0xFF6E528A)
val surfaceDimDark = Color(0xFF151216)
val surfaceBrightDark = Color(0xFF3B383C)
val surfaceContainerLowestDark = Color(0xFF100D11)
val surfaceContainerLowDark = Color(0xFF1D1B1F)
val surfaceContainerDark = Color(0xFF211F23)
val surfaceContainerHighDark = Color(0xFF2C292D)
val surfaceContainerHighestDark = Color(0xFF373438)
